import { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  CheckSquare,
  BarChart3,
  Database,
  Package,
  Wallet,
  ScrollText,
  Settings,
  Megaphone,
  Users,
  CreditCard,
  Clock,
  CalendarOff,
  MessageSquare,
  Target,
  UserCheck,
  Phone,
  DollarSign,
  Bell,
  Gift,
  Star,
  BookOpen,
  ShieldCheck,
  Send,
  Truck,
  AlertTriangle,
  Medal,
  PhoneCall,
  CalendarCheck,
  Trash2,
  Award,
  ShieldBan,
  RotateCcw,
} from "lucide-react";
import { PanelType } from "./panelConfig";

export interface SidebarItem {
  titleKey: string;
  icon: LucideIcon;
  path: string;
  /** If set, only show for these roles */
  roles?: string[];
}

export const sidebarMenus: Record<PanelType, SidebarItem[]> = {
  sa: [
    { titleKey: "dashboard", icon: LayoutDashboard, path: "/sa/dashboard" },
    { titleKey: "all_data", icon: Target, path: "/sa/all-data" },
    { titleKey: "data_tracker", icon: BarChart3, path: "/sa/data-tracker" },
    { titleKey: "approvals", icon: CheckSquare, path: "/sa/approvals" },
    { titleKey: "analytics", icon: BarChart3, path: "/sa/analytics" },
    { titleKey: "warehouse", icon: Package, path: "/sa/warehouse" },
    { titleKey: "budget", icon: Wallet, path: "/sa/budget" },
    { titleKey: "payroll", icon: CreditCard, path: "/sa/payroll" },
    { titleKey: "attendance", icon: Clock, path: "/sa/attendance" },
    { titleKey: "audit_logs", icon: ScrollText, path: "/sa/audit-logs" },
    { titleKey: "notifications", icon: Bell, path: "/sa/notifications" },
    { titleKey: "settings", icon: Settings, path: "/sa/settings" },
  ],
  hr: [
    { titleKey: "dashboard", icon: LayoutDashboard, path: "/hr/dashboard" },
    { titleKey: "approvals", icon: CheckSquare, path: "/hr/approvals" },
    { titleKey: "campaigns", icon: Megaphone, path: "/hr/campaigns" },
    { titleKey: "employees", icon: Users, path: "/hr/employees" },
    { titleKey: "data_operations", icon: Settings, path: "/hr/data-operations" },
    { titleKey: "data_monitor", icon: Target, path: "/hr/data-monitor" },
    { titleKey: "data_tracker", icon: BarChart3, path: "/hr/data-tracker" },
    { titleKey: "warehouse", icon: Package, path: "/hr/warehouse" },
    { titleKey: "payroll", icon: CreditCard, path: "/hr/payroll" },
    { titleKey: "attendance_leaves", icon: Clock, path: "/hr/attendance" },
    { titleKey: "my_attendance", icon: Clock, path: "/hr/my-attendance" },
    { titleKey: "customer_feedback", icon: Star, path: "/hr/feedback" },
    { titleKey: "complaints", icon: AlertTriangle, path: "/hr/complaints" },
    { titleKey: "chat", icon: MessageSquare, path: "/hr/chat" },
    { titleKey: "chat_admin", icon: Settings, path: "/hr/chat-admin" },
    { titleKey: "notifications", icon: Bell, path: "/hr/notifications" },
    { titleKey: "documentation", icon: BookOpen, path: "/hr/documentation" },
    { titleKey: "settings", icon: Settings, path: "/hr/settings" },
  ],
  tl: [
    { titleKey: "dashboard", icon: LayoutDashboard, path: "/tl/dashboard" },
    { titleKey: "leads", icon: Target, path: "/tl/leads" },
    { titleKey: "agent_activity", icon: Users, path: "/tl/leads/agent_activity" },
    { titleKey: "cso_pending", icon: ShieldCheck, path: "/tl/leads/cso" },
    { titleKey: "call_done", icon: PhoneCall, path: "/tl/leads/calldone" },
    { titleKey: "pre_orders", icon: CalendarCheck, path: "/tl/leads/preorders" },
    { titleKey: "silver_data", icon: Medal, path: "/tl/leads/silver" },
    { titleKey: "golden_data", icon: Award, path: "/tl/leads/golden" },
    { titleKey: "delete_sheet", icon: Trash2, path: "/tl/leads/deletesheet" },
    { titleKey: "spam", icon: ShieldBan, path: "/tl/spam", roles: ["team_leader", "Assistant Team Leader"] },
    { titleKey: "data_tracker", icon: BarChart3, path: "/tl/data-tracker", roles: ["team_leader", "Assistant Team Leader", "Business Development And Marketing Manager"] },
    { titleKey: "data_requests", icon: Database, path: "/tl/data-requests", roles: ["team_leader", "Assistant Team Leader", "Business Development And Marketing Manager"] },
    { titleKey: "my_leads", icon: Phone, path: "/tl/my-leads", roles: ["Assistant Team Leader"] },
    { titleKey: "my_orders", icon: Package, path: "/tl/my-orders", roles: ["Assistant Team Leader"] },
    { titleKey: "my_team", icon: UserCheck, path: "/tl/my-team", roles: ["team_leader", "Assistant Team Leader", "Business Development And Marketing Manager"] },
    { titleKey: "analytics", icon: BarChart3, path: "/tl/analytics", roles: ["team_leader", "Assistant Team Leader", "Business Development And Marketing Manager"] },
    { titleKey: "tl_approvals_bdo", icon: ShieldCheck, path: "/tl/agent-assignment", roles: ["Business Development And Marketing Manager"] },
    { titleKey: "atl_approvals", icon: ShieldCheck, path: "/tl/atl-approvals", roles: ["team_leader", "Assistant Team Leader"] },
    { titleKey: "attendance", icon: Clock, path: "/tl/attendance" },
    { titleKey: "salary", icon: DollarSign, path: "/tl/salary" },
    { titleKey: "chat", icon: MessageSquare, path: "/tl/chat" },
    { titleKey: "notifications", icon: Bell, path: "/tl/notifications" },
    { titleKey: "settings", icon: Settings, path: "/tl/settings" },
  ],
  employee: [
    { titleKey: "dashboard", icon: LayoutDashboard, path: "/employee/dashboard" },
    { titleKey: "leads", icon: Target, path: "/employee/leads", roles: ["telesales_executive", "silver_agent", "golden_agent", "cso"] },
    { titleKey: "leads", icon: Target, path: "/employee/cs-leads", roles: ["cs_executive"] },
    { titleKey: "cancellation_orders", icon: RotateCcw, path: "/employee/cancellation", roles: ["cancellation_executive", "Cancellation Executive"] },
    { titleKey: "my_orders", icon: Package, path: "/employee/my-orders", roles: ["telesales_executive", "silver_agent", "golden_agent"] },
    { titleKey: "spam", icon: ShieldBan, path: "/employee/spam", roles: ["telesales_executive", "silver_agent", "golden_agent", "cso"] },
    { titleKey: "steadfast_monitoring", icon: Truck, path: "/employee/steadfast", roles: ["delivery_coordinator"] },
    { titleKey: "order_dispatch", icon: Send, path: "/employee/dispatch", roles: ["warehouse_assistant", "warehouse_supervisor", "inventory_manager"] },
    { titleKey: "attendance", icon: Clock, path: "/employee/attendance" },
    { titleKey: "salary", icon: DollarSign, path: "/employee/salary" },
    { titleKey: "chat", icon: MessageSquare, path: "/employee/chat" },
    { titleKey: "notifications", icon: Bell, path: "/employee/notifications" },
    { titleKey: "settings", icon: Settings, path: "/employee/settings" },
  ],
};
